// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: juno/globalfee/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// TODO
type MsgTemporarilyOverrideFees struct {
	// TODO
	Coins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=coins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"coins"`
	// string FromAdd
	FromAddress string `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	// End time defines when this override will expire in unix seconds. TODO: is
	// this allowed because it is a time and machines may be different?
	EndTime uint64 `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (m *MsgTemporarilyOverrideFees) Reset()         { *m = MsgTemporarilyOverrideFees{} }
func (m *MsgTemporarilyOverrideFees) String() string { return proto.CompactTextString(m) }
func (*MsgTemporarilyOverrideFees) ProtoMessage()    {}
func (*MsgTemporarilyOverrideFees) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ca43707c1ad1a0, []int{0}
}
func (m *MsgTemporarilyOverrideFees) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTemporarilyOverrideFees) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTemporarilyOverrideFees.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTemporarilyOverrideFees) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTemporarilyOverrideFees.Merge(m, src)
}
func (m *MsgTemporarilyOverrideFees) XXX_Size() int {
	return m.Size()
}
func (m *MsgTemporarilyOverrideFees) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTemporarilyOverrideFees.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTemporarilyOverrideFees proto.InternalMessageInfo

func (m *MsgTemporarilyOverrideFees) GetCoins() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Coins
	}
	return nil
}

func (m *MsgTemporarilyOverrideFees) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgTemporarilyOverrideFees) GetEndTime() uint64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

// TODO
type MsgTemporarilyOverrideFeesResponse struct {
}

func (m *MsgTemporarilyOverrideFeesResponse) Reset()         { *m = MsgTemporarilyOverrideFeesResponse{} }
func (m *MsgTemporarilyOverrideFeesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTemporarilyOverrideFeesResponse) ProtoMessage()    {}
func (*MsgTemporarilyOverrideFeesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ca43707c1ad1a0, []int{1}
}
func (m *MsgTemporarilyOverrideFeesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTemporarilyOverrideFeesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTemporarilyOverrideFeesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTemporarilyOverrideFeesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTemporarilyOverrideFeesResponse.Merge(m, src)
}
func (m *MsgTemporarilyOverrideFeesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTemporarilyOverrideFeesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTemporarilyOverrideFeesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTemporarilyOverrideFeesResponse proto.InternalMessageInfo

// TODO
type MsgAddOverride struct {
	// string
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// overrides
	Amount uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgAddOverride) Reset()         { *m = MsgAddOverride{} }
func (m *MsgAddOverride) String() string { return proto.CompactTextString(m) }
func (*MsgAddOverride) ProtoMessage()    {}
func (*MsgAddOverride) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ca43707c1ad1a0, []int{2}
}
func (m *MsgAddOverride) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddOverride) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddOverride.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddOverride) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddOverride.Merge(m, src)
}
func (m *MsgAddOverride) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddOverride) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddOverride.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddOverride proto.InternalMessageInfo

func (m *MsgAddOverride) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgAddOverride) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// TODO
type MsgAddOverrideResponse struct {
}

func (m *MsgAddOverrideResponse) Reset()         { *m = MsgAddOverrideResponse{} }
func (m *MsgAddOverrideResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddOverrideResponse) ProtoMessage()    {}
func (*MsgAddOverrideResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39ca43707c1ad1a0, []int{3}
}
func (m *MsgAddOverrideResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddOverrideResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddOverrideResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddOverrideResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddOverrideResponse.Merge(m, src)
}
func (m *MsgAddOverrideResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddOverrideResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddOverrideResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddOverrideResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgTemporarilyOverrideFees)(nil), "juno.globalfee.MsgTemporarilyOverrideFees")
	proto.RegisterType((*MsgTemporarilyOverrideFeesResponse)(nil), "juno.globalfee.MsgTemporarilyOverrideFeesResponse")
	proto.RegisterType((*MsgAddOverride)(nil), "juno.globalfee.MsgAddOverride")
	proto.RegisterType((*MsgAddOverrideResponse)(nil), "juno.globalfee.MsgAddOverrideResponse")
}

func init() { proto.RegisterFile("juno/globalfee/tx.proto", fileDescriptor_39ca43707c1ad1a0) }

var fileDescriptor_39ca43707c1ad1a0 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xf5, 0x92, 0xd2, 0xc2, 0x16, 0xf5, 0x60, 0xa1, 0xd6, 0xf5, 0xc1, 0x0d, 0x16, 0x07, 0x0b,
	0x89, 0x5d, 0x12, 0xbe, 0xa0, 0x89, 0xc4, 0x05, 0x45, 0x48, 0x56, 0x4f, 0x5c, 0xaa, 0xb5, 0x77,
	0x6a, 0x0c, 0xf1, 0x8e, 0xb5, 0xb3, 0xa9, 0x9a, 0x1b, 0x9f, 0xc0, 0x77, 0xf0, 0x0f, 0xdc, 0x7b,
	0xec, 0x91, 0x13, 0xa0, 0xe4, 0x47, 0x90, 0xed, 0x18, 0x25, 0x87, 0x48, 0x9c, 0x76, 0x67, 0xde,
	0xec, 0x9b, 0xa7, 0x7d, 0x8f, 0x9f, 0x7d, 0x5e, 0x18, 0x94, 0xc5, 0x1c, 0x33, 0x35, 0xbf, 0x01,
	0x90, 0xee, 0x4e, 0xd4, 0x16, 0x1d, 0xfa, 0x27, 0x0d, 0x20, 0xfe, 0x01, 0xe1, 0xf3, 0x02, 0x0b,
	0x6c, 0x21, 0xd9, 0xdc, 0xba, 0xa9, 0x30, 0xca, 0x91, 0x2a, 0x24, 0x99, 0x29, 0x02, 0x79, 0x3b,
	0xca, 0xc0, 0xa9, 0x91, 0xcc, 0xb1, 0x34, 0x1d, 0x1e, 0xff, 0x60, 0x3c, 0x9c, 0x51, 0x71, 0x05,
	0x55, 0x8d, 0x56, 0xd9, 0x72, 0xbe, 0xfc, 0x70, 0x0b, 0xd6, 0x96, 0x1a, 0xde, 0x01, 0x90, 0xaf,
	0xf8, 0xe3, 0x66, 0x98, 0x02, 0x36, 0x1c, 0x24, 0xc7, 0xe3, 0x73, 0xd1, 0xd1, 0x89, 0x86, 0x4e,
	0x6c, 0xe8, 0xc4, 0x14, 0x4b, 0x33, 0x79, 0x73, 0xff, 0xeb, 0xc2, 0xfb, 0xfe, 0xfb, 0x22, 0x29,
	0x4a, 0xf7, 0x69, 0x91, 0x89, 0x1c, 0x2b, 0xb9, 0xd9, 0xdd, 0x1d, 0xaf, 0x49, 0x7f, 0x91, 0x6e,
	0x59, 0x03, 0xb5, 0x0f, 0x28, 0xed, 0x98, 0xfd, 0x17, 0xfc, 0xd9, 0x8d, 0xc5, 0xea, 0x5a, 0x69,
	0x6d, 0x81, 0x28, 0x78, 0x34, 0x64, 0xc9, 0xd3, 0xf4, 0xb8, 0xe9, 0x5d, 0x76, 0x2d, 0xff, 0x9c,
	0x3f, 0x01, 0xa3, 0xaf, 0x5d, 0x59, 0x41, 0x30, 0x18, 0xb2, 0xe4, 0x20, 0x3d, 0x02, 0xa3, 0xaf,
	0xca, 0x0a, 0xe2, 0x97, 0x3c, 0xde, 0x2f, 0x3f, 0x05, 0xaa, 0xd1, 0x10, 0xc4, 0x13, 0x7e, 0x32,
	0xa3, 0xe2, 0x52, 0xeb, 0x1e, 0xf5, 0x03, 0x7e, 0xd4, 0x2f, 0x64, 0xed, 0xc2, 0xbe, 0xf4, 0x4f,
	0xf9, 0xa1, 0xaa, 0x70, 0x61, 0x5c, 0xab, 0xe4, 0x20, 0xdd, 0x54, 0x71, 0xc0, 0x4f, 0x77, 0x39,
	0x7a, 0xf6, 0xf1, 0x57, 0xc6, 0x07, 0x33, 0x2a, 0xfc, 0x25, 0x3f, 0xdb, 0xf7, 0x8f, 0xaf, 0xc4,
	0xae, 0x5b, 0x62, 0xbf, 0xe8, 0x70, 0xfc, 0xff, 0xb3, 0xbd, 0x84, 0xc9, 0xfb, 0xfb, 0x55, 0xc4,
	0x1e, 0x56, 0x11, 0xfb, 0xb3, 0x8a, 0xd8, 0xb7, 0x75, 0xe4, 0x3d, 0xac, 0x23, 0xef, 0xe7, 0x3a,
	0xf2, 0x3e, 0x8e, 0xb6, 0xfc, 0x98, 0xb6, 0x46, 0x4c, 0xd1, 0x38, 0xab, 0x72, 0x47, 0xb2, 0x8d,
	0xd6, 0xdd, 0x76, 0xb8, 0x1a, 0x7b, 0xb2, 0xc3, 0x36, 0x1a, 0x6f, 0xff, 0x06, 0x00, 0x00, 0xff,
	0xff, 0xad, 0x34, 0xdb, 0x1b, 0x7b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// TODO
	TemporarilyOverrideFees(ctx context.Context, in *MsgTemporarilyOverrideFees, opts ...grpc.CallOption) (*MsgTemporarilyOverrideFeesResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) TemporarilyOverrideFees(ctx context.Context, in *MsgTemporarilyOverrideFees, opts ...grpc.CallOption) (*MsgTemporarilyOverrideFeesResponse, error) {
	out := new(MsgTemporarilyOverrideFeesResponse)
	err := c.cc.Invoke(ctx, "/juno.globalfee.Msg/TemporarilyOverrideFees", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// TODO
	TemporarilyOverrideFees(context.Context, *MsgTemporarilyOverrideFees) (*MsgTemporarilyOverrideFeesResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) TemporarilyOverrideFees(ctx context.Context, req *MsgTemporarilyOverrideFees) (*MsgTemporarilyOverrideFeesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TemporarilyOverrideFees not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_TemporarilyOverrideFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTemporarilyOverrideFees)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TemporarilyOverrideFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/juno.globalfee.Msg/TemporarilyOverrideFees",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TemporarilyOverrideFees(ctx, req.(*MsgTemporarilyOverrideFees))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "juno.globalfee.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TemporarilyOverrideFees",
			Handler:    _Msg_TemporarilyOverrideFees_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "juno/globalfee/tx.proto",
}

func (m *MsgTemporarilyOverrideFees) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTemporarilyOverrideFees) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTemporarilyOverrideFees) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EndTime != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EndTime))
		i--
		dAtA[i] = 0x18
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Coins) > 0 {
		for iNdEx := len(m.Coins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Coins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MsgTemporarilyOverrideFeesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTemporarilyOverrideFeesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTemporarilyOverrideFeesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAddOverride) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddOverride) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddOverride) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddOverrideResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddOverrideResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddOverrideResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgTemporarilyOverrideFees) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Coins) > 0 {
		for _, e := range m.Coins {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EndTime != 0 {
		n += 1 + sovTx(uint64(m.EndTime))
	}
	return n
}

func (m *MsgTemporarilyOverrideFeesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAddOverride) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTx(uint64(m.Amount))
	}
	return n
}

func (m *MsgAddOverrideResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgTemporarilyOverrideFees) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTemporarilyOverrideFees: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTemporarilyOverrideFees: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coins = append(m.Coins, types.Coin{})
			if err := m.Coins[len(m.Coins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			m.EndTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTemporarilyOverrideFeesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTemporarilyOverrideFeesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTemporarilyOverrideFeesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddOverride) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddOverride: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddOverride: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddOverrideResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddOverrideResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddOverrideResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
